return {
	bool_true_cclosure = true,
	
	bool_httpget = true,
	bool_http_redirect_to_known_proxies = true,
	
	bool_fake_compatibility = true,
	bool_standard_lib_extensions = true,
	
	bool_nil_parented_fake_script = true,
	bool_executor_mode = true,
	
	bool_instance_wrapping = true,
	bool_fake_cloneref = true,
	bool_filesystem = true,
	bool_metatable_manipulation = true,
	bool_decompiler = true,
	bool_detours = true,
	bool_teleport_queue = true,
	bool_allow_requiring_again = true,
	
	bool_fps_manipulation = true,
	bool_fps_uncap_at_zero = true,
	num_fps_cap = 720
}